//! Cross-language regression tests.
//!
//! Expected values are generated by `python_reference_generator.py` from the
//! Python implementation checked into this repository.  Python is deliberately
//! not invoked by these tests, so downstream Rust builds do not need NumPy,
//! SciPy, or Matplotlib installed.

use gammachirp_rs::gcfb_v211::{
    gammachirp::{self as gc, Carrier, Normalization},
    gcfb_v211::{self as fb211, AcfStatus, ControlMode as Control211, GcParam as Param211},
    utils as utils211,
};
use gammachirp_rs::gcfb_v234::{
    gcfb_v234::{
        self as fb234, ControlMode as Control234, DynHpaf, EmParam, GainReference,
        GcParam as Param234,
    },
    utils::{self as utils234, Floor, ParamTransFunc},
};
use ndarray::{Array2, ArrayView2};
use serde_json::Value;

const REFERENCE_JSON: &str = include_str!("fixtures/python_reference.json");

fn references() -> Value {
    serde_json::from_str(REFERENCE_JSON).expect("the checked-in Python fixture must be valid JSON")
}

fn expected_values(node: &Value) -> Vec<f64> {
    node["values"]
        .as_array()
        .expect("encoded array must contain values")
        .iter()
        .map(|value| value.as_f64().expect("fixture arrays contain numbers"))
        .collect()
}

fn expected_shape(node: &Value) -> Vec<usize> {
    node["shape"]
        .as_array()
        .expect("encoded array must contain a shape")
        .iter()
        .map(|value| value.as_u64().expect("shape entries are integers") as usize)
        .collect()
}

fn assert_values(label: &str, actual: &[f64], expected: &Value, atol: f64, rtol: f64) {
    let expected = expected_values(expected);
    assert_eq!(
        actual.len(),
        expected.len(),
        "{label}: Rust and Python lengths differ"
    );
    for (index, (&rust, &python)) in actual.iter().zip(&expected).enumerate() {
        let tolerance = atol + rtol * python.abs();
        assert!(
            rust.is_finite() && (rust - python).abs() <= tolerance,
            "{label}[{index}]: Rust {rust:.17e}, Python {python:.17e}, \
             difference {:.3e}, tolerance {tolerance:.3e}",
            (rust - python).abs()
        );
    }
}

fn assert_scalar(label: &str, actual: f64, expected: f64, atol: f64, rtol: f64) {
    let tolerance = atol + rtol * expected.abs();
    assert!(
        actual.is_finite() && (actual - expected).abs() <= tolerance,
        "{label}: Rust {actual:.17e}, Python {expected:.17e}, difference {:.3e}, tolerance {tolerance:.3e}",
        (actual - expected).abs()
    );
}

fn flattened(view: ArrayView2<'_, f64>) -> Vec<f64> {
    view.rows()
        .into_iter()
        .flat_map(|row| row.to_vec())
        .collect()
}

fn selected_rows(values: ArrayView2<'_, f64>, bins: &[usize]) -> Vec<f64> {
    let mut selected = Vec::with_capacity(values.nrows() * bins.len());
    for row in values.rows() {
        selected.extend(bins.iter().map(|&bin| row[bin]));
    }
    selected
}

fn v211_param(control: Control211) -> Param211 {
    Param211 {
        fs: 8_000.0,
        num_ch: 4,
        f_range: [200.0, 1_500.0],
        out_mid_crct: "No".into(),
        ctrl: control,
        ..Param211::default()
    }
}

fn v234_param(control: Control234, processing: &str, hearing_loss: &str) -> Param234 {
    Param234 {
        fs: 8_000.0,
        num_ch: 4,
        f_range: [200.0, 1_500.0],
        out_mid_crct: "No".into(),
        ctrl: control,
        dyn_hpaf: DynHpaf {
            str_prc: processing.into(),
            ..DynHpaf::default()
        },
        hloss_type: hearing_loss.into(),
        hloss_compression_health: (hearing_loss == "HL3").then_some(0.5),
        gain_ref: GainReference::NormalizeIoFunction,
        ..Param234::default()
    }
}

fn parity_input() -> Vec<f64> {
    let mut input = vec![0.0; 32];
    input[..6].copy_from_slice(&[1.0, -0.25, 0.5, 0.0, -0.1, 0.2]);
    input
}

#[test]
fn v211_scalar_scales_and_level_calibration_match_python() {
    let fixture = references();
    let scalar = &fixture["v211"]["utility_scalars"];
    let input = [-3.0, -1.0, 2.0, 4.0];
    assert_scalar(
        "rms",
        utils211::rms(&input),
        scalar["rms"].as_f64().unwrap(),
        1e-14,
        1e-14,
    );

    let powers: Vec<u64> = [1, 2, 3, 15, 16, 17, 1000]
        .map(|value| utils211::nextpow2(value) as u64)
        .to_vec();
    let expected_powers: Vec<u64> = scalar["nextpow2"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap())
        .collect();
    assert_eq!(powers, expected_powers);

    let mel: Vec<f64> = [50.0, 100.0, 1000.0, 6000.0]
        .map(utils211::freq2mel)
        .to_vec();
    assert_values("freq2mel", &mel, &scalar["freq2mel"], 1e-12, 1e-13);
    let frequency: Vec<f64> = [75.0, 500.0, 1000.0, 2500.0]
        .map(utils211::mel2freq)
        .to_vec();
    assert_values("mel2freq", &frequency, &scalar["mel2freq"], 1e-11, 1e-13);

    let erb_fixture = &fixture["v211"]["erb"];
    let (erb, width) = utils211::freq2erb(&[0.0, 50.0, 100.0, 1000.0, 6000.0]);
    assert_values(
        "ERB rate",
        erb.as_slice().unwrap(),
        &erb_fixture["rate"],
        1e-13,
        1e-13,
    );
    assert_values(
        "ERB width",
        width.as_slice().unwrap(),
        &erb_fixture["width"],
        1e-12,
        1e-13,
    );
    let (inverse, inverse_width) = utils211::erb2freq(erb.as_slice().unwrap());
    assert_values(
        "ERB inverse",
        inverse.as_slice().unwrap(),
        &erb_fixture["inverse_frequency"],
        1e-10,
        1e-13,
    );
    assert_values(
        "ERB inverse width",
        inverse_width.as_slice().unwrap(),
        &erb_fixture["inverse_width"],
        1e-11,
        1e-13,
    );

    let equal_fixture = &fixture["v211"]["equal_erb"];
    let (equal_frequency, equal_erb) =
        utils211::equal_freq_scale(utils211::FrequencyScale::Erb, 6, [100.0, 6000.0]).unwrap();
    assert_values(
        "equal ERB frequency",
        equal_frequency.as_slice().unwrap(),
        &equal_fixture["frequency"],
        1e-10,
        1e-13,
    );
    assert_values(
        "equal ERB scale",
        equal_erb.as_slice().unwrap(),
        &equal_fixture["erb"],
        1e-12,
        1e-13,
    );

    let (equalized, levels) = utils211::eqlz2meddis_hc_level(&input, 63.0).unwrap();
    let level_fixture = &fixture["v211"]["level_equalization"];
    assert_values(
        "v211 calibrated signal",
        equalized.as_slice().unwrap(),
        &level_fixture["signal"],
        1e-12,
        1e-13,
    );
    assert_values(
        "v211 calibration metadata",
        &levels,
        &level_fixture["level"],
        1e-12,
        1e-13,
    );
}

#[test]
fn v211_windows_filtering_and_framing_match_python() {
    let fixture = references();
    let windows = &fixture["v211"]["windows"];
    for (key, expected_name) in [
        ("HAM", "Hamming"),
        ("HAN", "Hanning/Cosine"),
        ("BLA", "Blackman"),
        ("LINE", "Line"),
    ] {
        let (window, name) = utils211::taper_window(12, key, Some(4), 3.0).unwrap();
        assert_eq!(name, expected_name);
        assert_eq!(windows[key]["name"].as_str().unwrap(), expected_name);
        assert_values(
            key,
            window.as_slice().unwrap(),
            &windows[key]["values"],
            1e-14,
            1e-13,
        );
    }

    let filtered = utils211::fftfilt(&[0.25, -0.5, 1.5, 0.75], &[1.0, -2.0, 0.5, 3.0, -1.0]);
    assert_values(
        "fftfilt",
        filtered.as_slice().unwrap(),
        &fixture["v211"]["fftfilt"],
        1e-13,
        1e-13,
    );

    let signal: Vec<f64> = (1..10).map(|value| value as f64).collect();
    let (frames, centers) = fb211::set_frame4time_sequence(&signal, 6, Some(3)).unwrap();
    let frame_fixture = &fixture["v211"]["frames"];
    assert_eq!(
        vec![frames.nrows(), frames.ncols()],
        expected_shape(&frame_fixture["values"])
    );
    assert_values(
        "framed signal",
        &flattened(frames.view()),
        &frame_fixture["values"],
        0.0,
        0.0,
    );
    let centers: Vec<f64> = centers.iter().map(|&value| value as f64).collect();
    assert_values(
        "frame centers",
        &centers,
        &frame_fixture["centers"],
        0.0,
        0.0,
    );
}

#[test]
fn v211_real_cepstrum_matches_python() {
    let fixture = references();
    let source = [1.0, 0.5, -0.25, 0.125, 0.75, -0.4, 0.2];
    let (cepstrum, minimum) = utils211::rceps(&source).unwrap();
    let expected = &fixture["v211"]["rceps"]["odd"];
    assert_values(
        "real cepstrum",
        cepstrum.as_slice().unwrap(),
        &expected["cepstrum"],
        2e-13,
        2e-13,
    );
    assert_values(
        "minimum phase reconstruction",
        minimum.as_slice().unwrap(),
        &expected["minimum_phase"],
        3e-13,
        3e-13,
    );
}

#[test]
fn v211_outer_middle_ear_tables_match_python() {
    let fixture = references();
    for kind in ["ELC", "MAF"] {
        let (power, frequency, db) = utils211::out_mid_crct(kind, 0, 48_000.0).unwrap();
        let expected = &fixture["v211"]["outer_middle_ear_tables"][kind];
        assert_values(
            &format!("{kind} power"),
            power.as_slice().unwrap(),
            &expected["power"],
            1e-14,
            1e-13,
        );
        assert_values(
            &format!("{kind} frequency"),
            frequency.as_slice().unwrap(),
            &expected["frequency"],
            0.0,
            0.0,
        );
        assert_values(
            &format!("{kind} dB"),
            db.as_slice().unwrap(),
            &expected["db"],
            0.0,
            0.0,
        );
    }
}

#[test]
fn gammachirp_impulses_and_carriers_match_python() {
    let fixture = references();
    for frequency in [500.0, 1500.0] {
        let output = gc::gammachirp(
            &[frequency],
            8_000.0,
            4.0,
            1.019,
            -2.0,
            0.3,
            Carrier::Cosine,
            Normalization::None,
        )
        .unwrap();
        let expected = &fixture["v211"]["gammachirp_impulse"][format!("{}", frequency as usize)];
        assert_values(
            "gammachirp impulse",
            &flattened(output.gc.view()),
            &expected["gc"],
            2e-13,
            2e-13,
        );
        let lengths: Vec<f64> = output.len_gc.iter().map(|&value| value as f64).collect();
        assert_values("gammachirp length", &lengths, &expected["length"], 0.0, 0.0);
        assert_values(
            "gammachirp peak",
            output.fps.as_slice().unwrap(),
            &expected["peak_frequency"],
            1e-11,
            1e-13,
        );
        assert_values(
            "instantaneous frequency",
            &flattened(output.inst_freq.view()),
            &expected["instantaneous_frequency"],
            1e-10,
            2e-13,
        );
    }

    let carriers = &fixture["v211"]["gammachirp_carriers"];
    for (name, carrier, normalization) in [
        ("peak_normalized", Carrier::Cosine, Normalization::Peak),
        ("envelope", Carrier::Envelope, Normalization::None),
        ("sine", Carrier::Sine, Normalization::None),
    ] {
        let output = gc::gammachirp(
            &[1000.0],
            8_000.0,
            4.0,
            1.019,
            -2.0,
            0.0,
            carrier,
            normalization,
        )
        .unwrap();
        assert_values(
            name,
            &flattened(output.gc.view()),
            &carriers[name],
            5e-13,
            5e-13,
        );
    }
}

#[test]
fn gammachirp_analytic_response_matches_python() {
    let fixture = references();
    let expected = &fixture["v211"]["gammachirp_response"];
    let bins: Vec<usize> = expected["bins"]
        .as_array()
        .unwrap()
        .iter()
        .map(|value| value.as_u64().unwrap() as usize)
        .collect();
    let response = gc::gammachirp_frsp(
        &[250.0, 1000.0, 3000.0],
        8_000.0,
        4.0,
        &[1.019],
        &[-2.0],
        0.25,
        256,
    )
    .unwrap();
    let frequency: Vec<f64> = bins.iter().map(|&bin| response.freq[bin]).collect();
    assert_values(
        "response frequency",
        &frequency,
        &expected["frequency"],
        0.0,
        0.0,
    );
    assert_values(
        "response amplitude",
        &selected_rows(response.amp_frsp.view(), &bins),
        &expected["amplitude"],
        2e-13,
        2e-13,
    );
    assert_values(
        "response peaks",
        response.f_peak.as_slice().unwrap(),
        &expected["peak_frequency"],
        1e-11,
        1e-13,
    );
    assert_values(
        "response group delay",
        &selected_rows(response.grp_dly.view(), &bins),
        &expected["group_delay"],
        2e-15,
        2e-13,
    );
    assert_values(
        "response phase",
        &selected_rows(response.phs_frsp.view(), &bins),
        &expected["phase"],
        2e-13,
        2e-13,
    );
}

#[test]
fn asymmetric_coefficients_and_stateful_filtering_match_python() {
    let fixture = references();
    let coefficients =
        fb211::make_asym_cmp_filters_v2(8_000.0, &[500.0, 1500.0], &[2.17, 1.8], &[2.2, 1.5])
            .unwrap();
    let expected = &fixture["v211"]["asymmetric_coefficients"];
    assert_values(
        "asymmetric poles",
        coefficients.ap.as_slice().unwrap(),
        &expected["ap"],
        3e-13,
        3e-13,
    );
    assert_values(
        "asymmetric zeros",
        coefficients.bz.as_slice().unwrap(),
        &expected["bz"],
        3e-13,
        3e-13,
    );

    let mut status = AcfStatus::new(&coefficients);
    let mut outputs = Vec::new();
    for input in [
        [1.0, -0.5],
        [0.0, 0.25],
        [-0.75, 0.0],
        [0.5, 1.0],
        [0.0, 0.0],
        [0.25, -0.25],
    ] {
        outputs.extend(status.process(&coefficients, &input, false).unwrap());
    }
    assert_eq!(status.count, 6);
    assert_values(
        "stateful asymmetric filter",
        &outputs,
        &fixture["v211"]["asymmetric_filter_sequence"],
        2e-12,
        5e-12,
    );
}

#[test]
fn asymmetric_and_compressive_frequency_responses_match_python() {
    let fixture = references();
    let expected_asym = &fixture["v211"]["asymmetric_response"];
    let bins: Vec<usize> = expected_asym["bins"]
        .as_array()
        .unwrap()
        .iter()
        .map(|value| value.as_u64().unwrap() as usize)
        .collect();
    let response =
        fb211::asym_cmp_frsp_v2(&[500.0, 1500.0], 8_000.0, &[2.17, 1.8], &[2.2, 1.5], 256, 4)
            .unwrap();
    assert_values(
        "ACF response",
        &selected_rows(response.acf_frsp.view(), &bins),
        &expected_asym["acf"],
        2e-10,
        2e-10,
    );
    assert_values(
        "asymmetric function",
        &selected_rows(response.asym_func.view(), &bins),
        &expected_asym["function"],
        2e-13,
        2e-13,
    );

    let expected = &fixture["v211"]["compressed_response"];
    let compressed = fb211::cmprs_gc_frsp(
        &[500.0, 1500.0],
        8_000.0,
        4.0,
        &[1.81, 1.7],
        &[-2.96, -2.5],
        &[0.9, 1.05],
        &[2.17, 1.9],
        &[2.2, 1.8],
        256,
    )
    .unwrap();
    assert_values(
        "compressed PGC",
        &selected_rows(compressed.pgc_frsp.view(), &bins),
        &expected["pgc"],
        3e-13,
        3e-13,
    );
    assert_values(
        "compressed CGC",
        &selected_rows(compressed.cgc_frsp.view(), &bins),
        &expected["cgc"],
        3e-13,
        3e-13,
    );
    assert_values(
        "normalized compressed response",
        &selected_rows(compressed.cgc_nrm_frsp.view(), &bins),
        &expected["normalized"],
        3e-13,
        3e-13,
    );
    for (label, actual, key) in [
        ("fp1", compressed.fp1.as_slice().unwrap(), "fp1"),
        ("fr2", compressed.fr2.as_slice().unwrap(), "fr2"),
        ("fp2", compressed.fp2.as_slice().unwrap(), "fp2"),
        (
            "peak value",
            compressed.val_fp2.as_slice().unwrap(),
            "peak_value",
        ),
        (
            "normalization",
            compressed.norm_fct_fp2.as_slice().unwrap(),
            "normalization",
        ),
    ] {
        assert_values(label, actual, &expected[key], 2e-11, 3e-13);
    }
}

#[test]
fn peak_frequency_conversions_match_python() {
    let fixture = references();
    let expected = expected_values(&fixture["v211"]["frequency_conversions"]);
    let mut actual = Vec::new();
    for fr1 in [250.0, 1000.0, 2500.0] {
        let (fp2, fr2) = fb211::fr1_to_fp2(4.0, 1.81, -2.96, 2.17, 2.2, 0.95, fr1).unwrap();
        let (inverse_fr1, inverse_fp1) =
            fb211::fp2_to_fr1(4.0, 1.81, -2.96, 2.17, 2.2, 0.95, fp2).unwrap();
        actual.extend([fr1, fp2, fr2, inverse_fr1, inverse_fp1]);
    }
    assert_eq!(actual.len(), expected.len());
    for row in 0..3 {
        assert_scalar(
            "conversion input",
            actual[row * 5],
            expected[row * 5],
            0.0,
            0.0,
        );
        for column in 1..5 {
            assert_scalar(
                "frequency conversion",
                actual[row * 5 + column],
                expected[row * 5 + column],
                3e-6,
                2e-9,
            );
        }
    }
}

#[test]
fn v211_derived_parameters_match_python() {
    let fixture = references();
    let expected = &fixture["v211"]["set_param"];
    let (param, response) = fb211::set_param(v211_param(Control211::Dynamic)).unwrap();
    for (label, actual, key) in [
        ("fr1", response.fr1.as_slice().unwrap(), "fr1"),
        ("ef", response.ef.as_slice().unwrap(), "ef"),
        ("b1", response.b1_val.as_slice().unwrap(), "b1"),
        ("c1", response.c1_val.as_slice().unwrap(), "c1"),
        ("fp1", response.fp1.as_slice().unwrap(), "fp1"),
        ("b2", response.b2_val.as_slice().unwrap(), "b2"),
        ("c2", response.c2_val.as_slice().unwrap(), "c2"),
    ] {
        assert_values(label, actual, &expected[key], 2e-11, 2e-13);
    }
    assert_scalar(
        "ERB spacing",
        response.erb_space1,
        expected["erb_space"].as_f64().unwrap(),
        1e-13,
        1e-13,
    );
    assert_scalar(
        "decay",
        param.lvl_est.exp_decay_val,
        expected["exp_decay"].as_f64().unwrap(),
        1e-14,
        1e-14,
    );
    assert_eq!(
        param.lvl_est.n_ch_shift as i64,
        expected["channel_shift"].as_f64().unwrap() as i64
    );
    let level_channels: Vec<f64> = param
        .lvl_est
        .n_ch_lvl_est
        .iter()
        .map(|&value| value as f64)
        .collect();
    assert_values(
        "level channels",
        &level_channels,
        &expected["level_channels"],
        0.0,
        0.0,
    );
    assert_scalar(
        "minimum linear level",
        param.lvl_est.lvl_lin_min_lim,
        expected["linear_minimum"].as_f64().unwrap(),
        1e-15,
        1e-14,
    );
    assert_scalar(
        "reference linear level",
        param.lvl_est.lvl_lin_ref,
        expected["linear_reference"].as_f64().unwrap(),
        1e-14,
        1e-14,
    );
}

fn assert_v211_filterbank(control: Control211, key: &str) {
    let fixture = references();
    let expected = &fixture["v211"]["filterbank"][key];
    let output = fb211::gcfb_v211(&parity_input(), v211_param(control)).unwrap();
    assert_values(
        "v211 CGC output",
        &flattened(output.cgc_out.view()),
        &expected["cgc"],
        2e-10,
        2e-9,
    );
    assert_values(
        "v211 PGC output",
        &flattened(output.pgc_out.view()),
        &expected["pgc"],
        2e-11,
        2e-10,
    );
    assert_values(
        "v211 fr2",
        &flattened(output.gc_resp.fr2.view()),
        &expected["fr2"],
        2e-7,
        2e-9,
    );
    assert_values(
        "v211 frequency ratio",
        &flattened(output.gc_resp.frat_val.view()),
        &expected["frat"],
        2e-10,
        2e-9,
    );
    assert_values(
        "v211 level",
        &flattened(output.gc_resp.lvl_db.view()),
        &expected["level_db"],
        2e-9,
        2e-9,
    );
    if !expected_values(&expected["gain"]).is_empty() {
        assert_values(
            "v211 gain",
            output.gc_resp.gain_factor.as_slice().unwrap(),
            &expected["gain"],
            2e-10,
            2e-9,
        );
    }
}

#[test]
fn v211_static_filterbank_matches_python_end_to_end() {
    assert_v211_filterbank(Control211::Static, "static");
}

#[test]
fn v211_dynamic_filterbank_matches_python_end_to_end() {
    assert_v211_filterbank(Control211::Dynamic, "dynamic");
}

#[test]
fn v234_level_interpolation_and_hearing_conversions_match_python() {
    let fixture = references();
    let expected = &fixture["v234"];
    let source = [0.25, -0.5, 0.75, -1.0];
    let (signal, levels) = utils234::eqlz2meddis_hc_level(&source, None, Some(94.0)).unwrap();
    assert_values(
        "precise calibrated signal",
        signal.as_slice().unwrap(),
        &expected["precise_level_equalization"]["signal"],
        1e-12,
        1e-13,
    );
    assert_values(
        "precise calibration metadata",
        &levels,
        &expected["precise_level_equalization"]["level"],
        1e-12,
        1e-13,
    );

    let inside =
        utils234::interp1(&[0.0, 1.0, 4.0], &[0.0, 2.0, -1.0], &[0.25, 2.5], false).unwrap();
    let outside =
        utils234::interp1(&[0.0, 1.0, 4.0], &[0.0, 2.0, -1.0], &[-2.0, 6.0], true).unwrap();
    assert_values(
        "interpolation",
        inside.as_slice().unwrap(),
        &expected["interpolation"]["inside"],
        1e-14,
        1e-14,
    );
    assert_values(
        "extrapolation",
        outside.as_slice().unwrap(),
        &expected["interpolation"]["extrapolated"],
        1e-14,
        1e-14,
    );

    let cases = [(125.0, 10.0), (1000.0, 20.0), (4000.0, 35.0), (8000.0, 5.0)];
    let spl: Vec<f64> = cases
        .iter()
        .map(|&(f, h)| utils234::hl2spl(f, h).unwrap())
        .collect();
    let cochlea: Vec<f64> = cases
        .iter()
        .map(|&(f, h)| utils234::hl2pin_cochlea(f, h).unwrap())
        .collect();
    let expected_spl: Vec<f64> = expected["hearing_level"]["spl"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap())
        .collect();
    let expected_cochlea: Vec<f64> = expected["hearing_level"]["cochlea"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap())
        .collect();
    assert_eq!(spl, expected_spl);
    assert_values(
        "cochlear input",
        &cochlea,
        &serde_json::json!({"values": expected_cochlea}),
        1e-13,
        1e-13,
    );

    let values = Array2::from_shape_vec((2, 3), vec![-0.1, 0.0, 0.02, 0.1, 0.5, 1.0]).unwrap();
    for (floor, key) in [(Floor::None, "none"), (Floor::ZeroFloor, "zero")] {
        let scaled = utils234::eqlz_gcfb2rms1_at_0db(&values, floor);
        assert_values(
            "absolute-threshold scaling",
            &flattened(scaled.view()),
            &expected["absolute_threshold_scaling"][key],
            2e-14,
            2e-13,
        );
    }
}

#[test]
fn v234_transfer_function_tables_match_python() {
    let fixture = references();
    let expected = &fixture["v234"];
    let (middle_frequency, middle_db) = utils234::trans_func_middle_ear_moore16();
    assert_values(
        "middle-ear frequencies",
        middle_frequency.as_slice().unwrap(),
        &expected["middle_ear_table"]["frequency"],
        0.0,
        0.0,
    );
    assert_values(
        "middle-ear response",
        middle_db.as_slice().unwrap(),
        &expected["middle_ear_table"]["db"],
        0.0,
        0.0,
    );

    for kind in ["FreeField", "DiffuseField"] {
        let (frequency, db) = utils234::trans_func_free_field2eardrum_moore16(kind).unwrap();
        assert_values(
            "field frequencies",
            frequency.as_slice().unwrap(),
            &expected["field_tables"][kind]["frequency"],
            0.0,
            0.0,
        );
        assert_values(
            "field response",
            db.as_slice().unwrap(),
            &expected["field_tables"][kind]["db"],
            0.0,
            0.0,
        );
    }
    let (frequency, db) = utils234::trans_func_free_field2eardrum_itu("ITU").unwrap();
    assert_values(
        "ITU frequencies",
        frequency.as_slice().unwrap(),
        &expected["field_tables"]["ITU"]["frequency"],
        0.0,
        0.0,
    );
    assert_values(
        "ITU response",
        db.as_slice().unwrap(),
        &expected["field_tables"]["ITU"]["db"],
        0.0,
        0.0,
    );
}

#[test]
fn v234_field_to_cochlea_response_matches_python() {
    let fixture = references();
    let expected = &fixture["v234"]["field_to_cochlea"];
    let transfer = utils234::trans_func_field2cochlea(&ParamTransFunc {
        fs: 16_000.0,
        n_frq_rsl: 64,
        freq_calib: 1000.0,
        type_field2eardrum: "FreeField".into(),
        type_midear2cochlea: "MiddleEar".into(),
        ..ParamTransFunc::default()
    })
    .unwrap();
    for (label, actual, key) in [
        (
            "transfer frequencies",
            transfer.freq.as_slice().unwrap(),
            "frequency",
        ),
        (
            "field transfer",
            transfer.field2eardrum_db.as_slice().unwrap(),
            "field_db",
        ),
        (
            "middle-ear transfer",
            transfer.midear2cochlea_db.as_slice().unwrap(),
            "middle_db",
        ),
        (
            "total transfer",
            transfer.field2cochlea_db.as_slice().unwrap(),
            "total_db",
        ),
    ] {
        assert_values(label, actual, &expected[key], 3e-12, 3e-12);
    }
    for (label, actual, key) in [
        (
            "calibration frequency",
            transfer.freq_calib,
            "frequency_calibration",
        ),
        (
            "field at calibration",
            transfer.field2eardrum_db_at_freq_calib,
            "field_at_calibration",
        ),
        (
            "field compensation",
            transfer.field2eardrum_db_cmpnst_db,
            "field_compensation",
        ),
        (
            "middle at calibration",
            transfer.midear2cochlea_db_at_freq_calib,
            "middle_at_calibration",
        ),
        (
            "total at calibration",
            transfer.field2cochlea_db_at_freq_calib,
            "total_at_calibration",
        ),
    ] {
        assert_scalar(label, actual, expected[key].as_f64().unwrap(), 3e-12, 3e-12);
    }
}

fn assert_v234_parameters(hearing_loss: &str) {
    let fixture = references();
    let expected = &fixture["v234"]["set_param"][hearing_loss];
    let (param, response) =
        fb234::set_param(v234_param(Control234::Dynamic, "frame-base", hearing_loss)).unwrap();
    for (label, actual, key) in [
        ("v234 fr1", response.fr1.as_slice().unwrap(), "fr1"),
        ("v234 fp1", response.fp1.as_slice().unwrap(), "fp1"),
        ("frat0", response.frat0_val.as_slice().unwrap(), "frat0"),
        ("frat1", response.frat1_val.as_slice().unwrap(), "frat1"),
        ("level center", response.pc_hpaf.as_slice().unwrap(), "pc"),
        (
            "centered ratio",
            response.frat0_pc.as_slice().unwrap(),
            "frat0_pc",
        ),
        (
            "frame window",
            param.dyn_hpaf.val_win.as_slice().unwrap(),
            "window",
        ),
        (
            "hearing level",
            param.hloss.hearing_level_db.as_slice().unwrap(),
            "hearing_level",
        ),
        (
            "active loss",
            param.hloss.pin_loss_db_act.as_slice().unwrap(),
            "active_loss",
        ),
        (
            "initial active loss",
            param.hloss.pin_loss_db_act_init.as_slice().unwrap(),
            "initial_active_loss",
        ),
        (
            "passive loss",
            param.hloss.pin_loss_db_pas.as_slice().unwrap(),
            "passive_loss",
        ),
        (
            "compression health",
            param.hloss.compression_health.as_slice().unwrap(),
            "health",
        ),
        (
            "gain compensation",
            param.hloss.af_gain_cmpnst_db.as_slice().unwrap(),
            "gain_compensation",
        ),
        (
            "filterbank hearing level",
            param.hloss.fb_hearing_level_db.as_slice().unwrap(),
            "fb_hearing_level",
        ),
        (
            "filterbank active loss",
            param.hloss.fb_pin_loss_db_act.as_slice().unwrap(),
            "fb_active_loss",
        ),
        (
            "filterbank passive loss",
            param.hloss.fb_pin_loss_db_pas.as_slice().unwrap(),
            "fb_passive_loss",
        ),
        (
            "filterbank health",
            param.hloss.fb_compression_health.as_slice().unwrap(),
            "fb_health",
        ),
        (
            "filterbank gain",
            param.hloss.fb_af_gain_cmpnst_db.as_slice().unwrap(),
            "fb_gain_compensation",
        ),
    ] {
        assert_values(label, actual, &expected[key], 4e-9, 4e-9);
    }
}

#[test]
fn v234_normal_hearing_parameters_match_python() {
    assert_v234_parameters("NH");
}

#[test]
fn v234_hl3_parameters_match_python() {
    assert_v234_parameters("HL3");
}

#[test]
fn v234_asymmetric_input_output_mapping_matches_python() {
    let fixture = references();
    let expected = &fixture["v234"]["asymmetric_io"];
    let (param, response) =
        fb234::set_param(v234_param(Control234::Dynamic, "frame-base", "NH")).unwrap();
    let pins = [-20.0, 0.0, 30.0, 60.0, 90.0, 120.0];
    let (asymmetry, output) =
        fb234::gcfb_v23_asym_func_in_out(&param, &response, 1000.0, 0.65, &pins);
    assert_values(
        "asymmetry I/O gain",
        asymmetry.as_slice().unwrap(),
        &expected["asymmetry_db"],
        2e-10,
        2e-10,
    );
    assert_values(
        "asymmetry I/O output",
        output.as_slice().unwrap(),
        &expected["output_db"],
        2e-10,
        2e-10,
    );
    let inverse: Vec<f64> = output
        .iter()
        .map(|&value| {
            fb234::gcfb_v23_asym_func_in_out_inv_io_func(&param, &response, 1000.0, 0.65, value)
                .unwrap()
        })
        .collect();
    assert_values(
        "inverse asymmetry I/O",
        &inverse,
        &expected["inverse"],
        3e-8,
        3e-9,
    );
}

#[test]
fn v234_modulation_filterbank_matches_python() {
    let fixture = references();
    let parameters = EmParam {
        fs: 2000.0,
        fc_mod_list: ndarray::arr1(&[1.0, 4.0, 16.0, 64.0]),
        ..EmParam::default()
    };
    let input = [1.0, 0.5, -0.25, 0.75, -1.0, 0.0, 0.2, -0.1, 0.3, 0.0];
    let output = fb234::gcfb_v23_env_mod_fb(&input, &parameters).unwrap();
    assert_values(
        "modulation filterbank",
        &flattened(output.view()),
        &fixture["v234"]["modulation_filterbank"],
        2e-12,
        2e-11,
    );
}

#[test]
fn v234_envelope_modulation_loss_matches_python() {
    let fixture = references();
    let expected = &fixture["v234"]["envelope_modulation_loss"];
    let parameters = fb234::set_param(v234_param(Control234::Dynamic, "frame-base", "NH"))
        .unwrap()
        .0;
    let frames = Array2::from_shape_fn((4, 16), |(channel, frame)| {
        let baseline = 1.25 + 0.35 * channel as f64;
        let modulation = (0.15 + 0.04 * channel as f64)
            * (2.0 * std::f64::consts::PI * (channel + 1) as f64 * frame as f64 / 16.0).sin();
        baseline + modulation + if frame == channel + 4 { 0.2 } else { 0.0 }
    });
    let (output, em) = fb234::gcfb_v23_env_mod_loss(
        &frames,
        &parameters,
        EmParam {
            reduce_db: ndarray::arr1(&[0.0, 3.0, 6.0, 9.0, 12.0, 15.0, 18.0]),
            f_cutoff: ndarray::arr1(&[32.0, 48.0, 64.0, 96.0, 128.0, 160.0, 192.0]),
            ..EmParam::default()
        },
    )
    .unwrap();

    assert_eq!(expected_shape(&expected["output"]), vec![4, 16]);
    assert_values(
        "envelope modulation loss",
        &flattened(output.view()),
        &expected["output"],
        3e-12,
        3e-12,
    );
    assert_scalar(
        "envelope modulation sampling rate",
        em.fs,
        expected["fs"].as_f64().unwrap(),
        0.0,
        0.0,
    );
    for (label, actual, key) in [
        (
            "envelope filterbank frequencies",
            em.fb_fr1.as_slice().unwrap(),
            "fb_fr1",
        ),
        (
            "interpolated envelope reductions",
            em.fb_reduce_db.as_slice().unwrap(),
            "fb_reduce_db",
        ),
        (
            "interpolated envelope cutoffs",
            em.fb_f_cutoff.as_slice().unwrap(),
            "fb_f_cutoff",
        ),
    ] {
        assert_values(label, actual, &expected[key], 3e-12, 3e-12);
    }
}

fn assert_v234_filterbank(key: &str, hearing_loss: &str) {
    let fixture = references();
    let expected = &fixture["v234"]["filterbank"][key];
    let output = fb234::gcfb_v234(
        &parity_input(),
        v234_param(Control234::Dynamic, "frame-base", hearing_loss),
    )
    .unwrap();
    assert_values(
        "v234 dcGC",
        &flattened(output.dcgc_out.view()),
        &expected["dcgc"],
        3e-8,
        4e-8,
    );
    assert_values(
        "v234 static sample GC",
        &flattened(output.scgc_smpl.view()),
        &expected["scgc"],
        3e-10,
        3e-9,
    );
    assert_values(
        "v234 fr2",
        &flattened(output.gc_resp.fr2.view()),
        &expected["fr2"],
        3e-7,
        3e-8,
    );
    assert_values(
        "v234 ratio",
        &flattened(output.gc_resp.frat_val.view()),
        &expected["frat"],
        3e-10,
        3e-8,
    );
    assert_values(
        "v234 sample level",
        &flattened(output.gc_resp.lvl_db.view()),
        &expected["level_db"],
        3e-9,
        3e-8,
    );
    assert_values(
        "v234 frame level",
        &flattened(output.gc_resp.lvl_db_frame.view()),
        &expected["level_db_frame"],
        3e-8,
        3e-8,
    );
    assert_values(
        "v234 PGC frames",
        &flattened(output.gc_resp.pgc_frame.view()),
        &expected["pgc_frame"],
        3e-10,
        3e-8,
    );
    assert_values(
        "v234 static GC frames",
        &flattened(output.gc_resp.scgc_frame.view()),
        &expected["scgc_frame"],
        3e-10,
        3e-8,
    );
    assert_values(
        "v234 asymmetry gain",
        &flattened(output.gc_resp.asym_func_gain.view()),
        &expected["asymmetry_gain"],
        3e-9,
        3e-8,
    );
    assert_values(
        "v234 output gain",
        output.gc_resp.gain_factor.as_slice().unwrap(),
        &expected["gain"],
        3e-9,
        3e-8,
    );
}

#[test]
fn v234_dynamic_frame_filterbank_matches_python_end_to_end() {
    assert_v234_filterbank("dynamic_frame", "NH");
}

#[test]
fn v234_hl3_dynamic_frame_filterbank_matches_python_end_to_end() {
    assert_v234_filterbank("dynamic_frame_hl3", "HL3");
}

#[test]
fn v234_no_correction_synthesis_matches_python() {
    let fixture = references();
    let input = Array2::from_shape_vec((4, 6), (1..=24).map(|value| value as f64 / 10.0).collect())
        .unwrap();
    let (param, _) = fb234::set_param(v234_param(Control234::Dynamic, "frame-base", "NH")).unwrap();
    let output = fb234::gcfb_v23_synth_snd(&input, &param).unwrap();
    assert_values(
        "v234 synthesis",
        output.as_slice().unwrap(),
        &fixture["v234"]["synthesis_no_correction"],
        1e-13,
        1e-13,
    );
}
